import cv2
import numpy as np
image = cv2.imread('new_text.png')
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
lower_black = np.array([0, 0, 0])
upper_black = np.array([180, 255, 50])
lower_white = np.array([0, 0, 200])
upper_white = np.array([180, 20, 255])
mask_black = cv2.inRange(hsv_image, lower_black, upper_black)
mask_white = cv2.inRange(hsv_image, lower_white, upper_white)
combined_mask = cv2.bitwise_or(mask_black, mask_white)
kernel = np.ones((5, 5), np.uint8)
dilated_black = cv2.dilate(mask_black, kernel, iterations=3)
dilated_white = cv2.dilate(mask_white, kernel, iterations=3)
black_details = cv2.connectedComponentsWithStats(dilated_black, connectivity=4)
white_details = cv2.connectedComponentsWithStats(dilated_white, connectivity=4)
print(f"Black text estimated word count: {black_details[0] - 1}")
print(f"White text estimated word count: {white_details[0] - 1}")
cv2.imshow('Black Mask', mask_black)
cv2.imshow('White Mask', mask_white)
cv2.imshow('Black Dilated', dilated_black)
cv2.imshow('White Dilated', dilated_white)
cv2.waitKey(0)
cv2.destroyAllWindows()